title:            @MIND LOG  내 마음의 항해일지
description:      Do Your Work. Don’t Be Stupid!
url: http://beatshon.github.io            # Site url.
signoff:   손병구      # Your name.
disqus_shortname: beatshon # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid: 267956736618918  # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: UA-29786791-1 # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
    
  - name:         life-LOG
    url:          https://brunch.co.kr/@beatshon7zxi
    external:     true
    
  - name:         Email
    url:          mailto:beatshon@gmail.com
    external:     true
    
  - name:         Topica
    url:          http://topica.tistory.com
    external:     true
    
 

pygments:         true
permalink:        pretty

markdown: kramdown
